# -*- coding: utf-8 -*-
"""RazorPay Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18oBz3FwD5VfZRi9SWpYcmtDmRjRD9O1j
"""

!pip install -q kaggle

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle

!cp kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d ealaxi/paysim1

!unzip -o paysim1.zip

import pandas as pd
df = pd.read_csv('PS_20174392719_1491204439457_log.csv')
print("Total rows:", len(df))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the dataset
df = pd.read_csv('PS_20174392719_1491204439457_log.csv')

# Quick shape check
print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
df.head()

print("Total transactions:", len(df))
print("\nFraud vs Non-fraud counts:")
print(df['isFraud'].value_counts())

print("\nFraud ratio (%):")
print(df['isFraud'].value_counts(normalize=True) * 100)

print("Transaction type counts:")
print(df['type'].value_counts())

print("\nFraud count by transaction type:")
fraud_by_type = df[df['isFraud'] == 1]['type'].value_counts()
print(fraud_by_type)

print("\nFraud rate WITHIN each type (%):")
fraud_rate_by_type = df.groupby('type')['isFraud'].mean() * 100
print(fraud_rate_by_type.sort_values(ascending=False))

fraud_rate_by_type.sort_values(ascending=False).plot(kind='bar', title='Fraud Rate by Transaction Type')
plt.ylabel('Fraud Rate (%)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('fraud_rate_by_type.png')
plt.show()

print("isFlaggedFraud counts:")
print(df['isFlaggedFraud'].value_counts())

# How well does this naive rule actually catch real fraud?
print("\nCross-tab: isFraud vs isFlaggedFraud")
print(pd.crosstab(df['isFraud'], df['isFlaggedFraud']))

actual_fraud = df[df['isFraud'] == 1]
caught_by_naive_rule = actual_fraud[actual_fraud['isFlaggedFraud'] == 1]
print(f"Naive rule catches {len(caught_by_naive_rule)} out of {len(actual_fraud)} fraud cases")
print(f"Naive rule recall: {len(caught_by_naive_rule)/len(actual_fraud)*100:.2f}%")

print("Step range:", df['step'].min(), "to", df['step'].max())
print("Number of unique steps:", df['step'].nunique())

# step = 1 hour in PaySim's simulation, so this tells you total simulated days
print("Total simulated days:", df['step'].max() / 24)

# Distribution of transactions per step
transactions_per_step = df.groupby('step').size()
transactions_per_step.plot(figsize=(14,4), title='Transactions per Step (hour)')
plt.xlabel('Step (hour)')
plt.ylabel('Transaction count')
plt.savefig('transactions_per_step.png')
plt.show()

# Fraud transactions per step — check if fraud clusters at certain times
fraud_per_step = df[df['isFraud']==1].groupby('step').size()
fraud_per_step.plot(figsize=(14,4), title='Fraud Transactions per Step (hour)', color='red')
plt.xlabel('Step (hour)')
plt.ylabel('Fraud count')
plt.savefig('fraud_per_step.png')
plt.show()

df.groupby('step').size().loc[395:420]  # look right at the transition point

df[(df['step']==210) & (df['isFraud']==1)][['type','amount','nameOrig','nameDest']]

df_filtered = df[df['type'].isin(['TRANSFER', 'CASH_OUT'])].copy()

print("Original shape:", df.shape)
print("Filtered shape:", df_filtered.shape)
print("\nFraud ratio in filtered data (%):")
print(df_filtered['isFraud'].value_counts(normalize=True) * 100)

# Save this filtered version so you don't need to reload/refilter every time
df_filtered.to_csv('paysim_filtered.csv', index=False)

# In legitimate transactions, oldbalanceOrg - amount should equal newbalanceOrig
df_filtered['balance_diff_orig'] = df_filtered['oldbalanceOrg'] - df_filtered['amount'] - df_filtered['newbalanceOrig']

print("Balance diff origin - stats for FRAUD vs NON-FRAUD:")
print(df_filtered.groupby('isFraud')['balance_diff_orig'].describe())

# Same check for destination account
df_filtered['balance_diff_dest'] = df_filtered['newbalanceDest'] - df_filtered['oldbalanceDest'] - df_filtered['amount']

print("\nBalance diff dest - stats for FRAUD vs NON-FRAUD:")
print(df_filtered.groupby('isFraud')['balance_diff_dest'].describe())

# Check how often destination balance is exactly 0 before AND after — common fraud pattern (mule accounts)
zero_balance_dest = df_filtered[(df_filtered['oldbalanceDest']==0) & (df_filtered['newbalanceDest']==0)]
print(f"\n% of fraud cases with zero balance dest (before & after): "
      f"{(zero_balance_dest['isFraud'].sum() / df_filtered['isFraud'].sum())*100:.2f}%")

fraud_rate_zero_dest = zero_balance_dest['isFraud'].mean()

print(
    f"Fraud rate among zero-balance destinations: "
    f"{fraud_rate_zero_dest * 100:.2f}%"
)

import pandas as pd

df_filtered = pd.read_csv('paysim_filtered.csv')

print("Shape:", df_filtered.shape)
print("Step range:", df_filtered['step'].min(), "-", df_filtered['step'].max())

df_filtered.to_pickle('paysim_filtered.pkl')

# Look at the distribution of steps to pick a sensible cutoff
print(df_filtered['step'].describe())

# Use the 80th percentile of step as the cutoff
split_step = df_filtered['step'].quantile(0.8)
print("Split at step:", split_step)

train_df = df_filtered[df_filtered['step'] <= split_step].copy()
test_df = df_filtered[df_filtered['step'] > split_step].copy()

print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

print("\nTrain fraud count:", train_df['isFraud'].sum(),
      " | Train fraud ratio (%):", train_df['isFraud'].mean()*100)
print("Test fraud count:", test_df['isFraud'].sum(),
      " | Test fraud ratio (%):", test_df['isFraud'].mean()*100)

print("Split step was:", split_step)

# Volume comparison
print("\nAvg transactions per step in TRAIN period:",
      train_df.groupby('step').size().mean())
print("Avg transactions per step in TEST period:",
      test_df.groupby('step').size().mean())

# Fraud count comparison
print("\nAvg fraud per step in TRAIN period:",
      train_df.groupby('step')['isFraud'].sum().mean())
print("Avg fraud per step in TEST period:",
      test_df.groupby('step')['isFraud'].sum().mean())

# Confirm no step overlap between train and test
print("Max train step:", train_df['step'].max())
print("Min test step:", test_df['step'].min())
# Min test step should be strictly greater than max train step

train_df.to_pickle('paysim_train.pkl')
test_df.to_pickle('paysim_test.pkl')

print("Saved train and test sets.")

scale_pos_weight = (train_df['isFraud']==0).sum() / (train_df['isFraud']==1).sum()
print("scale_pos_weight:", scale_pos_weight)

import pandas as pd

train_df = pd.read_pickle('paysim_train.pkl')
test_df = pd.read_pickle('paysim_test.pkl')

train_df['_split'] = 'train'
test_df['_split'] = 'test'

full_df = pd.concat([train_df, test_df], ignore_index=True)
full_df = full_df.sort_values(['step']).reset_index(drop=True)

print("Full shape:", full_df.shape)
print(full_df['_split'].value_counts())

import numpy as np

def build_velocity_features(df, window_steps=24):
    df = df.sort_values(['nameOrig', 'step']).reset_index(drop=True)

    df['prev_step'] = df.groupby('nameOrig')['step'].shift(1)
    df['time_since_last_txn'] = df['step'] - df['prev_step']
    df['time_since_last_txn'] = df['time_since_last_txn'].fillna(-1)

    counts = []
    for name, group in df.groupby('nameOrig', sort=False):
        steps = group['step'].values
        count_list = []
        for i, s in enumerate(steps):
            prior_steps = steps[:i]
            count_in_window = np.sum(prior_steps > (s - window_steps))
            count_list.append(count_in_window)
        counts.extend(count_list)

    df['txn_count_last_24step'] = counts
    df = df.drop(columns=['prev_step'])
    return df

import time
start = time.time()
full_df = build_velocity_features(full_df, window_steps=24)
print(f"Took {time.time()-start:.1f} seconds")

sample_account = full_df['nameOrig'].value_counts().index[0]
print(full_df[full_df['nameOrig']==sample_account][['step','txn_count_last_24step','time_since_last_txn']])

full_df['balance_diff_orig'] = full_df['oldbalanceOrg'] - full_df['amount'] - full_df['newbalanceOrig']

full_df['orig_balance_wiped'] = (full_df['newbalanceOrig'] == 0).astype(int)

full_df['dest_balance_zero_before_after'] = (
    (full_df['oldbalanceDest'] == 0) & (full_df['newbalanceDest'] == 0)
).astype(int)

full_df['amount_to_balance_ratio'] = full_df['amount'] / (full_df['oldbalanceOrg'] + 1)  # +1 avoids divide-by-zero

full_df['amount_to_dest_balance_ratio'] = full_df['amount'] / (full_df['oldbalanceDest'] + 1)

print(full_df[['balance_diff_orig','orig_balance_wiped','dest_balance_zero_before_after', 'amount_to_balance_ratio', 'amount_to_dest_balance_ratio']].describe())

feature_cols = ['amount','oldbalanceOrg','oldbalanceDest',
                 'balance_diff_orig','orig_balance_wiped',
                 'dest_balance_zero_before_after',
                 'txn_count_last_24step','time_since_last_txn', 'amount_to_dest_balance_ratio', 'amount_to_balance_ratio']

print(full_df[feature_cols + ['isFraud']].corr()['isFraud'].sort_values(ascending=False))

train_final = full_df[full_df['_split']=='train'].drop(columns=['_split'])
test_final = full_df[full_df['_split']=='test'].drop(columns=['_split'])

print("Train final shape:", train_final.shape)
print("Test final shape:", test_final.shape)

train_final.to_pickle('paysim_train_features.pkl')
test_final.to_pickle('paysim_test_features.pkl')

# Check: do fraud transactions mostly come from brand-new accounts?
print("Fraud rows with time_since_last_txn == -1 (first-ever transaction):")
print(full_df[full_df['isFraud']==1]['time_since_last_txn'].eq(-1).mean() * 100, "%")

print("\nNon-fraud rows with time_since_last_txn == -1:")
print(full_df[full_df['isFraud']==0]['time_since_last_txn'].eq(-1).mean() * 100, "%")

# Distribution of txn_count_last_24step for fraud vs non-fraud
print("\ntxn_count_last_24step - fraud:")
print(full_df[full_df['isFraud']==1]['txn_count_last_24step'].describe())

print("\ntxn_count_last_24step - non-fraud:")
print(full_df[full_df['isFraud']==0]['txn_count_last_24step'].describe())

# Drop the dead features before saving
train_final = train_final.drop(columns=['txn_count_last_24step', 'time_since_last_txn'])
test_final = test_final.drop(columns=['txn_count_last_24step', 'time_since_last_txn'])

train_final.to_pickle('paysim_train_features.pkl')
test_final.to_pickle('paysim_test_features.pkl')

print("Train final shape:", train_final.shape)
print("Test final shape:", test_final.shape)

import pandas as pd

train_final = pd.read_pickle('paysim_train_features.pkl')
test_final = pd.read_pickle('paysim_test_features.pkl')

print("Train shape:", train_final.shape)
print("Test shape:", test_final.shape)
print(train_final.columns.tolist())

feature_cols = ['amount', 'type', 'balance_diff_orig', 'orig_balance_wiped',
                 'dest_balance_zero_before_after', 'oldbalanceOrg', 'oldbalanceDest', 'amount_to_dest_balance_ratio', 'amount_to_balance_ratio']

X_train = train_final[feature_cols].copy()
y_train = train_final['isFraud']

X_test = test_final[feature_cols].copy()
y_test = test_final['isFraud']

# One-hot encode 'type' (TRANSFER/CASH_OUT)
X_train = pd.get_dummies(X_train, columns=['type'], drop_first=True)
X_test = pd.get_dummies(X_test, columns=['type'], drop_first=True)

# Make sure train/test have identical columns after encoding
X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

print("Final feature columns:", X_train.columns.tolist())
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

"""Training LightGBM starts

"""

!pip install -q lightgbm

import lightgbm as lgb

scale_pos_weight = (y_train==0).sum() / (y_train==1).sum()
print("Using scale_pos_weight:", scale_pos_weight)

base_model = lgb.LGBMClassifier(
    n_estimators=200,
    learning_rate=0.05,
    num_leaves=31,
    scale_pos_weight=scale_pos_weight,
    random_state=42
)

base_model.fit(X_train, y_train)
print("Training done.")

from sklearn.metrics import (classification_report, confusion_matrix,
                               roc_auc_score, precision_recall_curve, average_precision_score)

y_pred_proba = base_model.predict_proba(X_test)[:, 1]
y_pred_default = (y_pred_proba >= 0.5).astype(int)  # default 0.5 cutoff, we'll optimize this on Day 5

print("=== Classification Report (default 0.5 threshold) ===")
print(classification_report(y_test, y_pred_default, digits=4))

print("\n=== Confusion Matrix ===")
print(confusion_matrix(y_test, y_pred_default))

print("\n=== ROC-AUC ===")
print(roc_auc_score(y_test, y_pred_proba))

print("\n=== Average Precision (PR-AUC) ===")
print(average_precision_score(y_test, y_pred_proba))

import matplotlib.pyplot as plt

lgb.plot_importance(base_model, max_num_features=10, importance_type='gain')
plt.tight_layout()
plt.savefig('feature_importance.png')
plt.show()

import joblib
joblib.dump(base_model, 'base_model.pkl')
print("Base model saved.")

print(base_model.feature_importances_)
print(base_model.booster_.feature_importance(importance_type='gain'))
print(base_model.booster_.feature_importance(importance_type='split'))

import json
with open('feature_columns.json', 'w') as f:
    json.dump(X_train.columns.tolist(), f)

train_final = pd.read_pickle('paysim_train_features.pkl')
print("Fraud cases with amount=0 in TRAIN:", ((train_final['amount']==0) & (train_final['isFraud']==1)).sum())
print("Legit cases with amount=0 in TRAIN:", ((train_final['amount']==0) & (train_final['isFraud']==0)).sum())

